def node_app(app_name):
  docker_build('registry:5000/devops-lab-3/{}'.format(app_name), '../apps/', dockerfile='../apps/{}/Dockerfile'.format(app_name),
    only=['./{}'.format(app_name), './@shared'],
    live_update=[
      sync('../apps/{}'.format(app_name), '/src/{}'.format(app_name)),
      sync('../apps/@shared', '/src/@shared'),
      run('cd /src/{} && npm i'.format(app_name), trigger=['../apps/{}/package.json'.format(app_name), '../apps/{}/package-lock.json'.format(app_name)]),
      run('cd /src/@shared && npm i', trigger=['../apps/@shared/package.json', '../apps/@shared/package-lock.json'])
    ],
    entrypoint='npm run dev'
  )

apps = ['todos', 'webapp', 'users', 'auth', 'firestore-todos-sync']

[node_app(app_name) for app_name in apps]

# docker_build('registry:5000/devops-lab-3/kafka-to-sql', '../apps/kafka-to-sql')
docker_build('registry:5000/devops-lab-3/sql-source-connector', '../apps/sql-source-connector')
# docker_build('registry:5000/devops-lab-3/configure-kafka', '../apps/configure-kafka')
docker_build('registry:5000/devops-lab-3/sql-migrations', '../apps/sql-migrations', dockerfile='../apps/sql-migrations/dev.Dockerfile',
  live_update=[
    sync('../apps/sql-migrations', '/app')
  ])

k8s_yaml(listdir('./k8s-yamls', recursive=True))
